server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:fvc-api}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fvc-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}


  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:thanhldhe171856@fpt.edu.vn}
    password: ${SPRING_MAIL_PASSWORD:sylyjfmfxkzpkglh}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE:true}

  security:
    jwt:
      secret: ${SPRING_SECURITY_JWT_SECRET:b9f3c7e2a5d1f0c4b8a3e6d9f2c1a7b4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0}
      expiration: ${SPRING_SECURITY_JWT_EXPIRATION:18000000}

# Cấu hình logging
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER:TRACE}
    sep490g65.fvcapi: ${LOGGING_LEVEL_SEP490G65_FVCAPI:DEBUG}

# Các thuộc tính tùy chỉnh của ứng dụng
app:
  security:
    password-encoder:
      strength: ${APP_SECURITY_PASSWORD_ENCODER_STRENGTH:12}
    cors:
      allowed-origins: ${APP_SECURITY_CORS_ALLOWED_ORIGINS:http://localhost:5173}
      allowed-methods: ${APP_SECURITY_CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
      allowed-headers: ${APP_SECURITY_CORS_ALLOWED_HEADERS:*}
      allow-credentials: ${APP_SECURITY_CORS_ALLOW_CREDENTIALS:true}